name: Update Cattle Price Data Daily

on:
  schedule:
    # Executa todos os dias às 15:00 UTC (meio-dia no Brasil)
    - cron: '0 15 * * *'
  workflow_dispatch: # Permite a execução manual

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Find and run the data update script
        env:
          FIREBASE_CREDENTIALS_JSON: ${{ secrets.FIREBASE_CREDENTIALS }}
        run: |
          # Procura pelo script em qualquer pasta
          SCRIPT_PATH=$(find . -name "update_firestore.py")
          
          # Verifica se o script foi encontrado
          if [ -z "$SCRIPT_PATH" ]; then
            echo "ERRO: O ficheiro update_firestore.py não foi encontrado no repositório!"
            exit 1
          fi
          
          # Executa o script a partir do caminho encontrado
          echo "A executar o script encontrado em: $SCRIPT_PATH"
          python "$SCRIPT_PATH"
